java Script:

history of JS:
--> there was a company called Netscape,who has a own 
--> to provide the,which was run on thier browser's
--> Netscape company hired a developer called as  brenden Eich,where brenden eich invented a scripting language called as moka with in 10 days.
-->later on mocha rename as live script,and for the marketing perpose lie script renamed as java script.
-->JS was invented inthe year 1995,
-->Netscape company handovered ,JS to Ecma company(european computer manufacturer association).
-->where ecma company released ES-1 in the year 1997,every year ecam company releases new version of ecma script.

why JS:
--> Instead of providing a functionalities for the wedpage using server side logic,we can provide functionalities for 
   the webpage,which will provides functionalities and executes results on the webpage itself.

what is JS:
--> JS is  a scripting language, 
Reason -->bcz the JS code is red analysed and then executed
        --> its client server side Scrpting language,bcz The JS file is in Server side and functionalities is perform on the client's side.
it is called weakly type :  we dont a declare a date type to intialize to a variale,and semicolon is not mandatory 
--> its is dynamic Scripting language,bcz in JS variable can reintialized with different datatype,and we can declare a function and we can call the function,wherever we want dynamically.
--> Bieng Developer ,which means DRY principle(dont repeat yourself).
--> JS is  synchronous scripting language ,because JS code executed line by line from top to bottom and left to right.

NOte:

--> JS is  synchronous ,we can make it asynchronous
--> JS is single threaded ,becuase in JS  we have ,only one call stack
--> JS interpreted scripting language 
--> JS is Casesensitive language.


--> 





